AutoShopping/Areas/Admin/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoShopping.Models.ViewModel;
using AutoShopping.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Newtonsoft.Json;

namespace AutoShopping.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class CarController : Controller
    {
        private readonly IAutoRepository _repository;
        private readonly IHostingEnvironment _env;
        public CarController(IAutoRepository repository, IHostingEnvironment env)
        {
            _repository = repository;
            _env = env;
        }
        public async Task<IActionResult> Index(bool? status)
        {
            if (status != null)
            {
                if (status == true)
                {
                    ViewBag.success = true;
                }
                else if (status == false)
                {
                    ViewBag.success = false;
                }
            }

            var data = await _repository.GetAllCar();
            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> AddCar()
        {
            var model = await _repository.GetAllModels();
            var brand = await _repository.GetAllBrands();
            var color = await _repository.GetAllColor();

            var obj = new CarViewModel()
            {
                BrandList = new SelectList(brand, "ID", "BrandName"),
                ColorList = new SelectList(color, "ID", "ColorName"),
                ModelList = new SelectList(model, "ID", "ModelName")
            };

            return View(obj);
        }

        [HttpPost]
        public async Task<IActionResult> AddCar(CarViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel.CarImages = HttpContext.Request.Form.Files;

                var result = await _repository.AddCar(viewModel);
                if (result)
                    return RedirectToAction("Index", new RouteValueDictionary(new { status = result }));
            }

            var model = await _repository.GetAllModels();
            var brand = await _repository.GetAllBrands();
            var color = await _repository.GetAllColor();

            var obj = new CarViewModel()
            {
                BrandList = new SelectList(brand, "ID", "BrandName"),
                ColorList = new SelectList(color, "ID", "ColorName"),
                ModelList = new SelectList(model, "ID", "ModelName")
            };


            return View(obj);
        }

        [HttpGet]
        public async Task<IActionResult> EditCar(int? id)
        {
            var model = await _repository.GetAllModels();
            var brand = await _repository.GetAllBrands();
            var color = await _repository.GetAllColor();

            if (id != null)
            {
                var data = await _repository.GetCar(id);
                if (data.isAccept)
                {
                    data.CarViewModel.ModelList = new SelectList(model, "ID", "ModelName");
                    data.CarViewModel.BrandList = new SelectList(brand, "ID", "BrandName");
                    data.CarViewModel.ColorList = new SelectList(color, "ID", "ColorName");

                    return View(data.CarViewModel);
                }
            }
            return RedirectToAction("Index", new RouteValueDictionary(new { status = false }));
        }

        [HttpPost]
        public async Task<IActionResult> EditCar(CarViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var data = await _repository.UpdateCar(viewModel);
                if (data)
                {
                    return RedirectToAction("Index", new RouteValueDictionary(new { status = data }));
                }
            }
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> FilterModels(int brand)
        {
            var model = await _repository.GetAllModels();
            model = model.Where(p => p.BrandID == brand).ToList();

            return Json(JsonConvert.SerializeObject(model));
        }


        [HttpGet]
        public async Task<IActionResult> DeleteCar(int? id)
        {
            if (id != null)
            {
                var result = await _repository.GetCar(id);
                if (result.isAccept)
                {
                    return View(result.CarViewModel);
                }
            }

            return RedirectToAction("Index", new RouteValueDictionary(new { status = false }));
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCar(CarViewModel viewModel)
        {
            var data = await _repository.DeleteCar(viewModel);
            return RedirectToAction("Index", new RouteValueDictionary(new { status = data }));
        }
    }
}

AutoShopping/Areas/Admin/Views/Car/AddCar.cshtml
@model CarViewModel
@{
    ViewData["Title"] = "مدیریت ماشین ها";
}

<link href="~/lib/FileUpload/image-uploader.min.css" rel="stylesheet" />

<div class="col-10 bg-white mt-3 p-3 shadow">
    <form asp-area="Admin" asp-controller="Car" asp-action="AddCar" method="post" enctype="multipart/form-data">
        <div class="row form-group">
            <div class="col-4 text-right">
                <label asp-for="@Model.CategoryId"></label>
                <select asp-for="@Model.CategoryId" class="form-control">
                    <option value="">انتخاب کنید...</option>
                    <option value="1">سدان</option>
                    <option value="2">استیشن</option>
                    <option value="3">کوپه</option>
                    <option value="4">شاسی بلند</option>
                </select>
                <span asp-validation-for="@Model.CategoryId" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.ColorId"></label>
                <select asp-for="@Model.ColorId" asp-items="@Model.ColorList" class="form-control">
                    <option value="">انتخاب کنید...</option>
                </select>
                <span asp-validation-for="@Model.ColorId" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.BrandId"></label>
                <select id="Brand" asp-for="@Model.BrandId" asp-items="@Model.BrandList" class="form-control" onchange="filterModelList()">
                    <option value="">انتخاب کنید...</option>
                </select>
                <span asp-validation-for="@Model.BrandId" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.ModelId"></label>
                <select id="Model" asp-for="@Model.ModelId" asp-items="@Model.ModelList" class="form-control">
                    <option value="">انتخاب کنید...</option>
                </select>
                <span asp-validation-for="@Model.ModelId" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.Price"></label>
                <input type="number" asp-for="@Model.Price" class="form-control" value="" />
                <span asp-validation-for="@Model.Price" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.Quantity"></label>
                <input type="number" asp-for="@Model.Quantity" class="form-control" value="" />
                <span asp-validation-for="@Model.Quantity" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.CreateDate"></label>
                <input type="date" asp-for="@Model.CreateDate" class="form-control" value="" />
                <span asp-validation-for="@Model.CreateDate" class="text-danger"></span>
            </div>
            <div class="col-4">
                <label asp-for="@Model.CarImages"></label> <br />
                <div class="input-images"></div>
            </div>
            <div class="col-12">
                <input type="submit" class="btn btn-success" value="افزودن" />
                <a asp-area="Admin" asp-controller="Car" asp-action="Index" class="btn btn-danger">انصراف</a>
            </div>
        </div>
    </form>
</div>
@section Scripts{
    <script src="~/lib/FileUpload/image-uploader.js"></script>
    <script>
        function filterModelList() {
            var brand = $("#Brand");
            $.ajax({
                url: "/Admin/Car/FilterModels",
                type: "get",
                data: {
                    brand: brand.val(),
                },
                success: function (result) {
                    var data = JSON.parse(result)

                    var model = $("#Model");
                    model.empty();
                    model.append('<option value="">انتخاب کنید...</option>');
                    for (var i = 0; i < data.length; i++) {
                        model.append('<option value="' + data[i].ID + '">' + data[i].ModelName + '</option>')
                    }

                    $("#Model").removeAttr('disabled');
                }

            });
        }

        $('.input-images').imageUploader();
    </script>
}

AutoShopping/Areas/Admin/Views/Car/DeleteCar.cshtml
@model CarViewModel
@{
    ViewData["Title"] = "مدیریت ماشین ها";
}

<div class="col-10 bg-white mt-3 p-3 shadow">
    <form asp-area="Admin" asp-controller="Car" asp-action="DeleteCar" method="post">
        <div class="row form-group">
            <div class="col-4 text-right">
                <label asp-for="@Model.CategoryId"></label>
                <input asp-for="@Model.CategoryName" class="form-control"/>
                <span asp-validation-for="@Model.CategoryId" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.BrandId"></label>
                <input id="Brand" asp-for="@Model.BrandName" class="form-control"/>
                <span asp-validation-for="@Model.BrandId" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.ModelId"></label>
                <input id="Model" asp-for="@Model.ModelName" class="form-control" />
                <span asp-validation-for="@Model.ModelId" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.ColorId"></label>
                <input id="Model" asp-for="@Model.ColorName" class="form-control"/>
                <span asp-validation-for="@Model.ColorId" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.Price"></label>
                <input type="number" asp-for="@Model.Price" class="form-control" />
                <span asp-validation-for="@Model.Price" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.Quantity"></label>
                <input type="number" asp-for="@Model.Quantity" class="form-control" />
                <span asp-validation-for="@Model.Quantity" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.CreateDate"></label>
                <input type="date" asp-for="@Model.CreateDate" class="form-control" />
                <span asp-validation-for="@Model.CreateDate" class="text-danger"></span>
            </div>
            <div class="col-12 mt-4">
                <input type="submit" class="btn btn-danger" value="حذف" />
                <a asp-area="Admin" asp-controller="Car" asp-action="Index" class="btn btn-success">انصراف</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <script>
        function filterModelList() {
            var brand = $("#Brand");
            $.ajax({
                url: "/Admin/Car/FilterModels",
                type: "get",
                data: {
                    brand: brand.val(),
                },
                success: function (result) {
                    var data = JSON.parse(result)

                    var model = $("#Model");
                    model.empty();
                    model.append('<option value="">انتخاب کنید...</option>');
                    for (var i = 0; i < data.length; i++) {
                        model.append('<option value="' + data[i].ID + '">' + data[i].ModelName + '</option>')
                    }

                    $("#Model").removeAttr('disabled');
                }

            });
        }
    </script>
}

AutoShopping/Areas/Admin/Views/Car/EditCar.cshtml
@model CarViewModel
@{
    ViewData["Title"] = "مدیریت ماشین ها";
}

<div class="col-10 bg-white mt-3 p-3 shadow">
    <form asp-area="Admin" asp-controller="Car" asp-action="EditCar" method="post">
        <div class="row form-group">
            <div class="col-4 text-right">
                <label asp-for="@Model.CategoryId"></label>
                <select asp-for="@Model.CategoryId" class="form-control">
                    <option value="">انتخاب کنید...</option>
                    <option value="1">سدان</option>
                    <option value="2">استیشن</option>
                    <option value="3">کوپه</option>
                    <option value="4">شاسی بلند</option>
                </select>
                <span asp-validation-for="@Model.CategoryId" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.BrandId"></label>
                <select id="Brand" asp-for="@Model.BrandId" asp-items="@Model.BrandList" class="form-control" onchange="filterModelList()">
                    <option value="">انتخاب کنید...</option>
                </select>
                <span asp-validation-for="@Model.BrandId" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.ModelId"></label>
                <select id="Model" asp-for="@Model.ModelId" asp-items="@Model.ModelList" class="form-control">
                    <option value="">انتخاب کنید...</option>
                </select>
                <span asp-validation-for="@Model.ModelId" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.ColorId"></label>
                <select id="Model" asp-for="@Model.ColorId" asp-items="@Model.ColorList" class="form-control">
                    <option value="">انتخاب کنید...</option>
                </select>
                <span asp-validation-for="@Model.ColorId" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.Price"></label>
                <input type="number" asp-for="@Model.Price" class="form-control" />
                <span asp-validation-for="@Model.Price" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.Quantity"></label>
                <input type="number" asp-for="@Model.Quantity" class="form-control" />
                <span asp-validation-for="@Model.Quantity" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.CreateDate"></label>
                <input type="date" asp-for="@Model.CreateDate" class="form-control" />
                <span asp-validation-for="@Model.CreateDate" class="text-danger"></span>
            </div>
            <div class="col-12 mt-4">
                <input type="submit" class="btn btn-success" value="افزودن" />
                <a asp-area="Admin" asp-controller="Car" asp-action="Index" class="btn btn-danger">انصراف</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <script>
        function filterModelList() {
            var brand = $("#Brand");
            $.ajax({
                url: "/Admin/Car/FilterModels",
                type: "get",
                data: {
                    brand: brand.val(),
                },
                success: function (result) {
                    var data = JSON.parse(result)

                    var model = $("#Model");
                    model.empty();
                    model.append('<option value="">انتخاب کنید...</option>');
                    for (var i = 0; i < data.length; i++) {
                        model.append('<option value="' + data[i].ID + '">' + data[i].ModelName + '</option>')
                    }

                    $("#Model").removeAttr('disabled');
                }

            });
        }
    </script>
}

AutoShopping/Areas/Admin/Views/Car/Index.cshtml
@model IEnumerable<CarViewModel>
@{
    ViewData["Title"] = "افزودن ماشین";
}
    <link href="~/css/Color.css" rel="stylesheet" />
<div class="col-10 text-left">
    <a class="btn btn-outline-info mt-2" style="color: #000 !important;" asp-area="Admin" asp-controller="Car" asp-action="AddCar">افزودن ماشین جدید</a>
</div>
<div class="col-10 bg-white mt-3 shadow">
    <table class="table table-striped table-borderless text-center mt-1">
        <thead>
            <tr>
                <th>کد ماشین</th>
                <th>مدل</th>
                <th>برند</th>
                <th>دسته بندی</th>
                <th>رنگ</th>
                <th>تاریخ تولید</th>
                <th>قیمت</th>
                <th>موجودی</th>
                <th>عملیات</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.ID</td>
                    <td>@item.ModelName</td>
                    <td>@item.BrandName</td>
                    <td>@item.CategoryName</td>
                    <td>
                        <span class="ColorSpan" style="background-color: @item.ColorCode">
                        </span>
                    </td>
                    <td>@item.CreateDate</td>
                    <td>@item.Price</td>
                    <td>@item.Quantity</td>
                    <td>
                        <a asp-area="Admin" asp-controller="Car" asp-action="EditCar" asp-route-id="@item.ID">ویرایش</a>
                        <span>|</span>
                        <a asp-area="Admin" asp-controller="Car" asp-action="DeleteCar" asp-route-id="@item.ID">حذف</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>