AutoShopping/Models/AutoShopping.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoShopping.Models
{
    public class User
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string City { get; set; }
        public int Country { get; set; }
        public string Address { get; set; }
        public List<Order> Orders { get; set; }
        public int RoleId { get; set; }
        public Role Role { get; set; }
        public List<Ticket> Tickets { get; set; }
    }

    public class Role
    {
        public int ID { get; set; }
        public string RoleName { get; set; }
        public List<User> Users { get; set; }
    }

    public class Status
    {
        public int ID { get; set; }
        public string StatusName { get; set; }
        public List<Ticket> Tickets { get; set; }
    }

    public class Brand
    {
        public int ID { get; set; }
        public string BrandName { get; set; }
        public string LogoNameImg { set; get; }
        public List<Model> Models { get; set; }
    }

    public class Model
    {
        public int ID { get; set; }
        public string ModelName { get; set; }
        public int BrandID { get; set; }
        public Brand Brand { get; set; }
        public List<Car> Cars { get; set; }
    }

    public class Color
    {
        public int ID { get; set; }
        public string ColorName { get; set; }
        public string ColorCode { get; set; }
        public List<Car> Cars { get; set; }
    }

    public class Category
    {
        public int ID { get; set; }
        public string CategoryName { get; set; }
        public List<Car> Cars { get; set; }
    }

    public class Car
    {
        public int ID { get; set; }
        public DateTime CreateDate { get; set; }
        public int Price { get; set; }
        public int Quantity { get; set; }
        public int ColorId { get; set; }
        public Color Color { get; set; }
        public int ModelId { get; set; }
        public Model Model { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        public List<OrderDetail> OrderDetails { get; set; }
        public string FileNameImage { get; set; }
        public List<Images> Images { get; set; }
    }

    public class Order
    {
        public int ID { get; set; }
        public DateTime OrderDate { get; set; }
        public int UserId { get; set; }
        public User User { get; set; }
        public List<OrderDetail> OrderDetails { get; set; }
    }

    public class OrderDetail
    {
        public int ID { get; set; }
        public int CarId { get; set; }
        public Car Car { get; set; }
        public int Price { get; set; }
        public int Discount { get; set; }
        public int Quantity { get; set; }
        public int OrderId { get; set; }
        public Order Order { get; set; }
    }

    public class Ticket
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public User User { get; set; }
        public string Title { get; set; }
        public int StatusId { get; set; }
        public Status Status { get; set; }
        public DateTime CreateDate { get; set; }
        public List<TicketDetails> TicketDetails { get; set; }
    }

    public class TicketDetails
    {
        public int ID { get; set; }
        public int TicketId { get; set; }
        public Ticket Ticket { get; set; }
        public int UserId { get; set; }
        public DateTime Date { get; set; }
        public string Description { get; set; }
    }

    public class Images
    {
        public int ID { get; set; }
        public int CarID { get; set; }
        public string Name { get; set; }
        public Car Car { get; set; }
    }
}

AutoShopping/Models/AutoShoppingDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoShopping.Models.Mapping;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace AutoShopping.Models
{
    public class AutoShoppingDbContext : IdentityDbContext
    {

        public IPasswordHasher<IdentityUser> _passwordHasher { get; }

        public AutoShoppingDbContext(IPasswordHasher<IdentityUser> passwordHasher)
        {
            _passwordHasher = passwordHasher;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server =.; DataBase= AutoShopping ; Trusted_Connection=true;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Category>().HasData(new Category() {ID = 1, CategoryName = "سدان"});
            modelBuilder.Entity<Category>().HasData(new Category() {ID = 2, CategoryName = "کوپه"});
            modelBuilder.Entity<Category>().HasData(new Category() {ID = 3, CategoryName = "استیشن"});
            modelBuilder.Entity<Category>().HasData(new Category() {ID = 4, CategoryName = "شاسی بلند"});


            #region Mapping
            modelBuilder.ApplyConfiguration(new UserMapping());
            modelBuilder.ApplyConfiguration(new TicketMapping());
            modelBuilder.ApplyConfiguration(new CarMapping());
            #endregion

            #region RoleTableFluents
            modelBuilder.Entity<Role>().HasKey(p => p.ID);
            modelBuilder.Entity<Role>().Property(p => p.ID)
                .ValueGeneratedOnAdd()
                .IsRequired();
            modelBuilder.Entity<Role>().Property(p => p.RoleName)
                .IsRequired();
            #endregion

            #region StatusTableFluents
            modelBuilder.Entity<Status>().HasKey(p => p.ID);
            modelBuilder.Entity<Status>().Property(p => p.ID)
                .ValueGeneratedOnAdd()
                .IsRequired();
            modelBuilder.Entity<Status>().Property(p => p.StatusName)
                .IsRequired();
            #endregion

            #region BrandTableFluents
            modelBuilder.Entity<Brand>().HasKey(p => p.ID);
            modelBuilder.Entity<Brand>().Property(p => p.ID)
                .ValueGeneratedOnAdd()
                .IsRequired();
            modelBuilder.Entity<Brand>().Property(p => p.BrandName)
                .IsRequired()
                .HasColumnType("nVarChar(20)");

            modelBuilder.Entity<Brand>().HasMany(p => p.Models).WithOne(p => p.Brand).HasForeignKey(p => p.BrandID).OnDelete(DeleteBehavior.Restrict);
            #endregion

            #region ModelTableFluents
            modelBuilder.Entity<Model>().HasKey(p => p.ID);
            modelBuilder.Entity<Model>().Property(p => p.ID)
                .ValueGeneratedOnAdd()
                .IsRequired();
            modelBuilder.Entity<Model>().Property(p => p.ModelName)
                .IsRequired()
                .HasColumnType("nVarChar(20)");
            modelBuilder.Entity<Model>().Property(p => p.BrandID)
                .IsRequired();
            #endregion

            #region ColorTableFluents
            modelBuilder.Entity<Color>().HasKey(p => p.ID);
            modelBuilder.Entity<Color>().Property(p => p.ID)
                .IsRequired()
                .ValueGeneratedOnAdd();
            modelBuilder.Entity<Color>().Property(p => p.ColorName)
                .IsRequired()
                .HasColumnType("nVarChar(20)");
            modelBuilder.Entity<Color>().Property(p => p.ColorCode)
                .IsRequired()
                .HasColumnType("nVarChar(10)");
            #endregion

            #region CategoryTableFluents
            modelBuilder.Entity<Category>().HasKey(p => p.ID);
            modelBuilder.Entity<Category>().Property(p => p.ID)
                .ValueGeneratedOnAdd()
                .IsRequired();
            modelBuilder.Entity<Category>().Property(p => p.CategoryName)
                .IsRequired();
            #endregion

            #region OrderTableFluents
            modelBuilder.Entity<Order>().HasKey(p => p.ID);
            modelBuilder.Entity<Order>().Property(p => p.ID)
                .ValueGeneratedOnAdd()
                .IsRequired();
            modelBuilder.Entity<Order>().Property(p => p.OrderDate)
                .IsRequired();
            modelBuilder.Entity<Order>().Property(p => p.UserId)
                .IsRequired();

            modelBuilder.Entity<Order>().HasMany(p => p.OrderDetails).WithOne(p => p.Order).HasForeignKey(p => p.OrderId);

            #endregion

            #region OrderDetailsTableFluents
            modelBuilder.Entity<OrderDetail>().HasKey(p => p.ID);
            modelBuilder.Entity<OrderDetail>().Property(p => p.ID)
                .ValueGeneratedOnAdd()
                .IsRequired();
            modelBuilder.Entity<OrderDetail>().Property(p => p.CarId)
                .IsRequired();
            modelBuilder.Entity<OrderDetail>().Property(p => p.Price)
                .IsRequired();
            modelBuilder.Entity<OrderDetail>().Property(p => p.Quantity)
                .IsRequired();
            modelBuilder.Entity<OrderDetail>().Property(p => p.OrderId)
                .IsRequired();
            #endregion

            #region TicketDetailsTableFluents
            modelBuilder.Entity<TicketDetails>().HasKey(p => p.ID);
            modelBuilder.Entity<TicketDetails>().Property(p => p.ID)
                .ValueGeneratedOnAdd()
                .IsRequired();
            modelBuilder.Entity<TicketDetails>().Property(p => p.TicketId)
                .IsRequired();
            modelBuilder.Entity<TicketDetails>().Property(p => p.UserId)
                .IsRequired();
            modelBuilder.Entity<TicketDetails>().Property(p => p.Date)
                .IsRequired();
            #endregion

            #region ImageTableFluents
            modelBuilder.Entity<Images>().HasKey(p => p.ID);
            modelBuilder.Entity<Images>().Property(p => p.CarID)
                .IsRequired();
            modelBuilder.Entity<Images>().Property(p => p.Name)
                .IsRequired();
            #endregion
        }

        #region Dbset
        public DbSet<User> Users { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Status> Statuses { get; set; }
        public DbSet<Brand> Brands { get; set; }
        public DbSet<Model> Models { get; set; }
        public DbSet<Color> Colors { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Car> Cars { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderDetail> orderDetails { get; set; }
        public DbSet<Ticket> Tickets { get; set; }
        public DbSet<TicketDetails> TicketDetails { get; set; }
        public DbSet<Images> Images { get; set; }
        
        #endregion

    }

    
}

AutoShopping/Models/ErrorViewModel.cs
using System;

namespace AutoShopping.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AutoShopping/Models/Mapping/CarMapping.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoShopping.Models.Mapping
{
    public class CarMapping : IEntityTypeConfiguration<Car>
    {
        public void Configure(EntityTypeBuilder<Car> builder)
        {
            builder.HasKey(p => p.ID);
            builder.Property(p => p.ID).UseIdentityColumn(1251,1);
            builder.Property(p => p.ID).ValueGeneratedOnAdd().IsRequired();
            builder.Property(p => p.CreateDate).IsRequired();
            builder.Property(p => p.Price).IsRequired();
            builder.Property(p => p.Quantity).IsRequired();
            builder.Property(p => p.ColorId).IsRequired();
            builder.Property(p => p.ModelId).IsRequired();
            builder.Property(p => p.CategoryId).IsRequired();

            builder.HasOne(p => p.Model).WithMany(p => p.Cars).HasForeignKey(p => p.ModelId);
            builder.HasOne(p => p.Color).WithMany(p => p.Cars).HasForeignKey(p => p.ColorId);
            builder.HasOne(p => p.Category).WithMany(p => p.Cars).HasForeignKey(p => p.CategoryId);
            builder.HasMany(p => p.OrderDetails).WithOne(p => p.Car).HasForeignKey(p => p.CarId);
            builder.HasMany(p => p.Images).WithOne(p => p.Car).HasForeignKey(p => p.CarID);
        }
    }
}

AutoShopping/Models/Mapping/TicketMapping.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoShopping.Models.Mapping
{
    public class TicketMapping : IEntityTypeConfiguration<Ticket>
    {
        public void Configure(EntityTypeBuilder<Ticket> builder)
        {
            builder.HasKey(p => p.ID);
            builder.Property(p => p.ID).ValueGeneratedOnAdd().IsRequired();
            builder.Property(p => p.UserId).IsRequired();
            builder.Property(p => p.Title).IsRequired();
            builder.Property(p => p.StatusId).IsRequired();
            builder.Property(p => p.CreateDate).IsRequired();

            builder.HasOne(p => p.Status).WithMany(p => p.Tickets).HasForeignKey(p => p.StatusId);
            builder.HasMany(p => p.TicketDetails).WithOne(p => p.Ticket).HasForeignKey(p => p.TicketId);
        }
    }
}

AutoShopping/Areas/Admin/Controllers/ModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoShopping.Models.ViewModel;
using AutoShopping.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;

namespace AutoShopping.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class ModelController : Controller
    {
        private readonly IAutoRepository _repository;
        public ModelController(IAutoRepository repository)
        {
            _repository = repository;
        }

        public async Task<IActionResult> Index(bool? status)
        {
            if (status != null)
            {
                if (status == true)
                {
                    ViewBag.success = true;
                }
                else if (status == false)
                {
                    ViewBag.success = false;
                }
            }

            var data = await _repository.GetAllModels();

            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> AddModel()
        {
            var result = await _repository.GetAllBrands();
            var obj = new ModelViewModel();

            obj.BrandList = new SelectList(result, "ID", "BrandName");

            return View(obj);
        }

        [HttpPost]
        public async Task<IActionResult> AddModel(ModelViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                bool result = await _repository.AddNewModel(viewModel);
                return RedirectToAction("Index", new RouteValueDictionary(new { status = result }));
            }
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> EditModel(int? id)
        {
            if (id != null)
            {
                var data = await _repository.GetModel(id);
                if (data.isAccept)
                {
                    var obj = await _repository.GetAllBrands();
                    data.Model.BrandList = new SelectList(obj, "ID", "BrandName");
                    return View(data.Model);
                }
                return RedirectToAction("Index", new RouteValueDictionary(new { status = data.isAccept }));
            }

            return RedirectToAction("Index", new RouteValueDictionary(new { status = false }));
        }

        [HttpPost]
        public async Task<IActionResult> EditModel(ModelViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                bool result = await _repository.UpdateModel(viewModel);

                return RedirectToAction("Index", new RouteValueDictionary(new { status = result }));
            }

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteModel(int? id)
        {
            if (id != null)
            {
                var data = await _repository.GetModel(id);
                if (data.isAccept)
                    return View(data.Model);
                return RedirectToAction("Index", new RouteValueDictionary(new { status = data.isAccept }));
            }

            return RedirectToAction("Index", new RouteValueDictionary(new { status = false }));
        }

        [HttpPost]
        public async Task<IActionResult> DeleteModel(ModelViewModel viewModel)
        {
            var result = await _repository.DeleteModel(viewModel);
            return RedirectToAction("Index", new RouteValueDictionary(new { status = result }));
        }
    }
}

AutoShopping/Areas/Admin/Views/Model/AddModel.cshtml
@model ModelViewModel
@{
    ViewData["Title"] = "مدیریت مدل ها";
}

<div class="col-10 bg-white mt-3 p-3 shadow">
    <form asp-area="Admin" asp-controller="Model" asp-action="AddModel" method="post">
        <div class="row form-group">
            <div class="col-4 text-right">
                <label asp-for="@Model.ModelName"></label>
                <input type="text" asp-for="@Model.ModelName" class="form-control" />
                <span asp-validation-for="@Model.ModelName" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.BrandID"></label>
                <select asp-for="@Model.BrandID" asp-items="@Model.BrandList" class="form-control">
                    <option value="">انتخاب کنید...</option>
                </select>
                <span asp-validation-for="@Model.BrandID" class="text-danger"></span>
            </div>
            <div class="col-12">
                <input type="submit" class="btn btn-success" value="افزودن" />
                <a asp-area="Admin" asp-controller="Model" asp-action="Index" class="btn btn-danger">انصراف</a>
            </div>
        </div>
    </form>
</div>

AutoShopping/Areas/Admin/Views/Model/DeleteModel.cshtml
@model ModelViewModel
@{
    ViewData["Title"] = "مدیریت مدل ها";
}

    <div class="col-10 bg-white mt-3 p-3 shadow">
        <form asp-area="Admin" asp-controller="Model" asp-action="DeleteModel" method="post">
            <div class="row form-group">
                <div class="col-4 text-right">
                    <label asp-for="@Model.ModelName"></label>
                    <input type="text" asp-for="@Model.ModelName" class="form-control" />
                    <span asp-validation-for="@Model.ModelName" class="text-danger"></span>
                </div>
                <div class="col-4 text-right">
                    <label asp-for="@Model.BrandID"></label>
                    <input type="text" asp-for="@Model.BrandName" class="form-control" />
                    <span asp-validation-for="@Model.BrandID" class="text-danger"></span>
                </div>
                <div class="col-12">
                    <input type="submit" class="btn btn-success" value="حذف" />
                    <a asp-area="Admin" asp-controller="Model" asp-action="Index" class="btn btn-danger">انصراف</a>
                </div>
            </div>
        </form>
    </div>

AutoShopping/Areas/Admin/Views/Model/EditModel.cshtml
@model ModelViewModel
@{
    ViewData["Title"] = "مدیریت مدل ها";
}

<div class="col-10 bg-white mt-3 p-3 shadow">
    <form asp-area="Admin" asp-controller="Model" asp-action="EditModel" method="post">
        <div class="row form-group">
            <div class="col-4 text-right">
                <label asp-for="@Model.ModelName"></label>
                <input type="text" asp-for="@Model.ModelName" class="form-control" />
                <span asp-validation-for="@Model.ModelName" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.BrandID"></label>
                    <select asp-for="@Model.BrandID" asp-items="@Model.BrandList" class="form-control">
                        <option value="">انتخاب کنید ...</option>
                    </select>
                <span asp-validation-for="@Model.BrandID" class="text-danger"></span>
            </div>
            <div class="col-12">
                <input type="submit" class="btn btn-success" value="افزودن" />
                <a asp-area="Admin" asp-controller="Model" asp-action="Index" class="btn btn-danger">انصراف</a>
            </div>
        </div>
    </form>
</div>

AutoShopping/Areas/Admin/Views/Model/Index.cshtml
@model IEnumerable<ModelViewModel>
@{
    ViewData["Title"] = "مدیریت مدل ها";
}

<style>
    tbody tr td{
        vertical-align: middle !important;
    }
</style>

<div class="col-10 text-left">
    <a class="btn btn-outline-info mt-2" style="color: #000 !important;" asp-area="Admin" asp-controller="Model" asp-action="AddModel">افزودن مدل جدید</a>
</div>
<div class="col-10 bg-white mt-3 shadow">
    <table class="table table-striped table-borderless text-center mt-1">
        <thead>
            <tr>
                <th>کد مدل</th>
                <th>نام مدل</th>
                <th>برند</th>
                <th>عملیات</th>
            </tr>
        </thead>
        <tbody >
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.ID</td>
                    <td>@item.ModelName</td>
                    <td>
                        @{
                            if (item.BrandLogo != null)
                            {
                                <img class="img-thumbnail" style="width: 100px; height: 100px; object-fit: contain;" src="~/GalleryFile/Brand/@item.BrandLogo" />
                                <br />
                                <span>@item.BrandName</span>
                            }
                            else
                            {
                                <img class="img-thumbnail" style="width: 100px; height: 100px; object-fit: contain;" src="~/Images/DefaultCar.png" />
                            }
                        }
                    </td>
                    <td>
                        <a asp-area="Admin" asp-controller="Model" asp-action="EditModel" asp-route-id="@item.ID">ویرایش</a>
                        <span>|</span>
                        <a asp-area="Admin" asp-controller="Model" asp-action="DeleteModel" asp-route-id="@item.ID">حذف</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>