AutoShopping/Areas/Admin/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoShopping.Models.ViewModel;
using AutoShopping.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;

namespace AutoShopping.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class BrandController : Controller
    {
        private readonly IAutoRepository _repository;
        public BrandController(IAutoRepository repository)
        {
            _repository = repository;
        }
        public async Task<IActionResult> Index(bool? status)
        {
            if(status != null)
            {
                if (status == true)
                {
                    ViewBag.success = true;
                }
                else if (status == false)
                {
                    ViewBag.success = false;
                }
            }

            var data = await _repository.GetAllBrands();
            return View(data);
        }

        public IActionResult Addbrand() => View();

        [HttpPost]
        public async Task<IActionResult> AddBrand(BrandViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                bool result = await _repository.AddNewBrand(viewModel);
                return RedirectToAction("Index", new RouteValueDictionary(new { status = result }));
            }

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> EditBrand(int? id)
        {
            if (id != null)
            {
                var data = await _repository.GetBrand(id);
                if (data.isAccept)
                {
                    return View(data.Brand);
                }
                return RedirectToAction("Index", new RouteValueDictionary(new { status = data.isAccept }));
            }

            return RedirectToAction("Index", new RouteValueDictionary(new { status = false }));
        }

        [HttpPost]
        public async Task<IActionResult> EditBrand(BrandViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await _repository.UpdateBrand(viewModel);
                return RedirectToAction("Index", new RouteValueDictionary(new { status = true }));
            }

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteBrand(int? id)
        {
            if (id != null)
            {
                var data = await _repository.GetBrand(id);
                if (data.isAccept)
                {
                    return View(data.Brand);
                }
                return RedirectToAction("Index", new RouteValueDictionary(new { status = data.isAccept }));
            }

            return RedirectToAction("Index", new RouteValueDictionary(new { status = false }));
        }

        [HttpPost]
        public async Task<IActionResult> DeleteBrand(BrandViewModel viewModel)
        {
            var data = await _repository.DeleteBrand(viewModel);
            return RedirectToAction("Index", new RouteValueDictionary(new { status = data }));
        }
    }
}

AutoShopping/Areas/Admin/Views/Brand/Addbrand.cshtml
@model BrandViewModel
@{
    ViewData["Title"] = "مدیریت برند ها";
}

<style>
    .file {
        visibility: hidden;
        position: absolute;
    }
</style>

<div class="col-10 bg-white mt-3 p-3 shadow">
    <form asp-area="Admin" asp-controller="Brand" asp-action="AddBrand" method="post" enctype="multipart/form-data">
        <div class="row form-group">
            <div class="col-4 text-right">
                <label asp-for="@Model.BrandName"></label>
                <input type="text" asp-for="@Model.BrandName" class="form-control" />
                <span asp-validation-for="@Model.BrandName" class="text-danger"></span>
            </div>
            <div class="col-4 text-right">
                <label asp-for="@Model.LogoImg"></label> <br />
                <input type="file" class="file" accept="image/*" asp-for="@Model.LogoImg">
                <div class="input-group">
                    <div class="input-group-append">
                        <button type="button" class="browse btn btn-primary">انتخاب...</button>
                    </div>
                    <input type="text" class="form-control" disabled placeholder="آپلود عکس" id="file" style="border-radius: 15px 0 0 15px;">
                </div>
                <span asp-validation-for="@Model.LogoImg" class="text-danger"></span>
            </div>
            <div class="mt-3">
                <img style="width: 200px; height: 200px; object-fit: contain;" src="~/Images/DefaultCar.png" id="preview" class="img-thumbnail">
            </div>
            <div class="col-12">
                <input type="submit" class="btn btn-success" value="افزودن" />
                <a asp-area="Admin" asp-controller="Brand" asp-action="Index" class="btn btn-danger">انصراف</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <script>
        $(document).on("click", ".browse", function () {
            var file = $(this).parents().find(".file");
            file.trigger("click");
        });
        $('input[type="file"]').change(function (e) {
            var fileName = e.target.files[0].name;
            $("#file").val(fileName);

            var reader = new FileReader();
            reader.onload = function (e) {
                // get loaded data and render thumbnail.
                document.getElementById("preview").src = e.target.result;
            };
            // read the image file as a data URL.
            reader.readAsDataURL(this.files[0]);
        });
    </script>
}

AutoShopping/Areas/Admin/Views/Brand/DeleteBrand.cshtml
@model BrandViewModel
@{
    ViewData["Title"] = "مدیریت برند ها";
}

<div class="col-10 bg-white mt-3 p-3 shadow">
    <form asp-area="Admin" asp-controller="Brand" asp-action="DeleteBrand" method="post" enctype="multipart/form-data">
        <div class="row form-group">
            <div class="col-4 text-right">
                <label asp-for="@Model.BrandName"></label>
                <input type="text" asp-for="@Model.BrandName" class="form-control" />
                <span asp-validation-for="@Model.BrandName" class="text-danger"></span>
            </div>
            <div class="mt-3">
                @{
                    if (Model.LogoFileName != null)
                    {
                        <img class="img-thumbnail" style="width: 200px; height: 200px; object-fit: contain;" src="~/GalleryFile/Brand/@Model.LogoFileName" />
                    }
                    else
                    {
                        <img class="img-thumbnail" style="width: 200px; height: 200px; object-fit: contain;" src="~/Images/DefaultCar.png" />
                    }
                }
            </div>
            <div class="col-12">
                <input type="submit" class="btn btn-success" value="حذف" />
                <a asp-area="Admin" asp-controller="Brand" asp-action="Index" class="btn btn-danger">انصراف</a>
            </div>
        </div>
    </form>
</div>

AutoShopping/Areas/Admin/Views/Brand/EditBrand.cshtml
@model BrandViewModel
@{
    ViewData["Title"] = "مدیریت برند ها";
}

<style>
    .file {
        visibility: hidden;
        position: absolute;
    }
</style>

<div class="col-10 bg-white mt-3 p-3 shadow">
    <form asp-area="Admin" asp-controller="Brand" asp-action="EditBrand" method="post" enctype="multipart/form-data">
        <div class="row form-group" style="line-height:3;">
            <div class="col-4 text-right">
                <label asp-for="@Model.BrandName"></label>
                <input type="text" asp-for="@Model.BrandName" class="form-control" />
                <span asp-validation-for="@Model.BrandName" class="text-danger"></span>
            </div>
            <div class="col-3 text-center">
                <label asp-for="@Model.LogoImg"></label> <br />
                @{
                    if (Model.LogoFileName != null)
                    {
                        <img style="width: 200px; height: 200px; object-fit: contain;" src="~/GalleryFile/Brand/@Model.LogoFileName" id="preview" class="img-thumbnail">
                    }
                    else
                    {
                        <img style="width: 200px; height: 200px; object-fit: contain;" id="preview" src="~/Images/DefaultCar.png" />
                    }
                }<br />
                <input id="img" type="file" class="file" accept="image/*" asp-for="@Model.LogoImg">
                <button type="button" class="browse btn btn-primary">تغییر...</button>
                <a class="btn btn-warning" onclick="removeImg()">حذف عکس</a>
                <span asp-validation-for="@Model.LogoImg" class="text-danger"></span>
            </div>
            <div class="col-12">
                <input type="submit" class="btn btn-success" value="ثبت تغییرات" />
                <a asp-area="Admin" asp-controller="Brand" asp-action="Index" class="btn btn-danger">انصراف</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <script>
        $(document).on("click", ".browse", function () {
            var file = $(this).parents().find(".file");
            file.trigger("click");
        });
        $('input[type="file"]').change(function (e) {
            var fileName = e.target.files[0].name;
            $("#file").val(fileName);

            var reader = new FileReader();
            reader.onload = function (e) {
                // get loaded data and render thumbnail.
                document.getElementById("preview").src = e.target.result;
            };
            // read the image file as a data URL.
            reader.readAsDataURL(this.files[0]);
        });

        function removeImg() {
            $("#img").val("");
            $("#preview").attr("src", "/Images/DefaultCar.png");
        }
    </script>
}

AutoShopping/Areas/Admin/Views/Brand/Index.cshtml
@model IEnumerable<BrandViewModel>
@{
    ViewData["Title"] = "مدیریت برند ها";

    var resutl = ViewBag.success;
}

<div class="col-10 text-left">
    <a class="btn btn-outline-info mt-2" style="color: #000 !important;" asp-area="Admin" asp-controller="Brand" asp-action="AddBrand">افزودن برند جدید</a>
</div>


<div class="col-10 bg-white mt-3 mb-5 shadow">
    <table class="table table-striped table-borderless text-center mt-1">
        <thead>
            <tr>
                <th>کد برند</th>
                <th>عکس</th>
                <th>نام برند</th>
                <th>عملیات</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr style="line-height:7">
                <td>@item.ID</td>
                <td>
                    @{
                        if (item.LogoFileName != null)
                        {
                            <img class="img-thumbnail" style="width: 100px; height: 100px; object-fit: contain;" src="~/GalleryFile/Brand/@item.LogoFileName" />
                        }
                        else
                        {
                            <img class="img-thumbnail" style="width: 100px; height: 100px; object-fit: contain;" src="~/Images/DefaultCar.png" />
                        }
                    }
                </td>
                <td>@item.BrandName</td>
                <td>
                    <a asp-area="Admin" asp-controller="Brand" asp-action="EditBrand" asp-route-id="@item.ID">ویرایش</a>
                    <span>|</span>
                    <a asp-area="Admin" asp-controller="Brand" asp-action="DeleteBrand" asp-route-id="@item.ID">حذف</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>