AutoShopping/Controllers/ManageRoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoShopping.Models.ViewModel.Account;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AutoShopping.Controllers
{
    [Authorize]
    public class ManageRoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public ManageRoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();

            return View(roles);
        }

        [HttpGet]
        public IActionResult AddRole() => View();

        [HttpPost]
        public async Task<IActionResult> AddRole(RoleViewModel viewModel)
        {
            if(ModelState.IsValid)
            {
                var role = new IdentityRole(viewModel.Name);
                var result = await _roleManager.CreateAsync(role);
                if (result.Succeeded) return RedirectToAction("Index");

                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, item.Description);
                }
            }

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var role = await _roleManager.FindByIdAsync(id);
            
            if (role == null) return NotFound();

            var data = new RoleViewModel()
            {
                Id = role.Id,
                Name = role.Name
            };

            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditRole(RoleViewModel viewModel)
        {
            if(ModelState.IsValid)
            {
                var role = await _roleManager.FindByIdAsync(viewModel.Id);
                if (role == null) return NotFound();

                role.Name = viewModel.Name;

                var result = await _roleManager.UpdateAsync(role);
                if (result.Succeeded) return RedirectToAction("Index");

                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, item.Description);
                }
            }

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var role = await _roleManager.FindByIdAsync(id);

            if (role == null) return NotFound();

            var data = new RoleViewModel()
            {
                Id = role.Id,
                Name = role.Name
            };

            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteRole(RoleViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var role = await _roleManager.FindByIdAsync(viewModel.Id);
                if (role == null) return NotFound();

                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded) return RedirectToAction("Index");

                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, item.Description);
                }
            }

            return View(viewModel);
        }
    }
}

AutoShopping/Controllers/ManageUserController.cs
using System.Linq;
using System.Threading.Tasks;
using AutoShopping.Models.ViewModel.Account;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoShopping.Controllers
{
    public class ManageUserController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public ManageUserController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var users = _userManager.Users.Select(s => new UserViewModel()
            {
                Id = s.Id,
                UserName = s.UserName,
                Email = s.Email
            }).ToList();

            return View(users);
        }


        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var user = await _userManager.FindByIdAsync(id);

            if (user == null) return NotFound();

            var data = new UserViewModel()
            {
                Id = user.Id,
                UserName = user.UserName,
                Email = user.Email
            };

            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUser(UserViewModel viewModel)
        {
            if(ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(viewModel.Id);

                if (user == null) RedirectToAction("Index");

                user.UserName = viewModel.UserName;
                user.Email = viewModel.Email;

                var result = await _userManager.UpdateAsync(user);

                if (result.Succeeded) return RedirectToAction("Index");

                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, item.Description);
                }
            }

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> AddUserToRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();

            var roles = _roleManager.Roles.AsTracking().Select(s => s.Name).ToList();
            var userRoles = await _userManager.GetRolesAsync(user);
            var validRoles = roles.Where(p => userRoles.Contains(p))
                .Select(r => new UserRolesViewModel(r)).ToList();
            var model = new AddUserToRoleViewModel(id,validRoles);

            //foreach (var role in roles)
            //{
            //    if(!await _userManager.IsInRoleAsync(user,role.Name))
            //    {
            //        model.userRoles.Add(new UserRolesViewModel()
            //        {
            //            RoleName = role.Name,
            //            IsSelected = false
            //        });
            //    }
            //    else
            //    {
            //        model.userRoles.Add(new UserRolesViewModel()
            //        {
            //            RoleName = role.Name,
            //            IsSelected = true
            //        });
            //    }
            //}

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUserToRole(AddUserToRoleViewModel viewModel)
        {
            if(ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(viewModel.UserId);
                if (user == null) return NotFound();

                var requestRole = viewModel.UserRoles.Where(p => p.IsSelected)
                    .Select(s => s.RoleName)
                    .ToList();

                var result = await _userManager.AddToRolesAsync(user, requestRole);
                if (result.Succeeded) return RedirectToAction("Index");

                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, item.Description);
                }
            }

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteUser(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var user = await _userManager.FindByIdAsync(id);

            if (user == null) return NotFound();

            var data = new UserViewModel()
            {
                Id = user.Id,
                UserName = user.UserName,
                Email = user.Email
            };

            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUser(UserViewModel viewModel)
        {
            if(ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(viewModel.Id);
                if (user == null) return NotFound();

                var result = await _userManager.DeleteAsync(user);

                if(result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, item.Description);
                }
            }

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> RemoveUserFromRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();

            var roles = await _userManager.GetRolesAsync(user);
            var validRoles = roles.Select(s => new UserRolesViewModel(s)).ToList();

            var model = new AddUserToRoleViewModel(id,validRoles);

            //foreach (var item in roles)
            //{
            //    if(await _userManager.IsInRoleAsync(user,item.Name))
            //    {
            //        model.userRoles.Add(new UserRolesViewModel()
            //        {
            //            RoleName = item.Name
            //        });
            //    }
            //}

            return View(model);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveUserFromRole(AddUserToRoleViewModel viewModel)
        {
            if(ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(viewModel.UserId);
                if (user == null) return NotFound();

                var requestRoles = viewModel.UserRoles.Where(p => p.IsSelected)
                    .Select(s => s.RoleName)
                    .ToList();

                var result = await _userManager.RemoveFromRolesAsync(user,requestRoles);

                if(result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, item.Description);
                }
                
            }

            return View(viewModel);
        }

        
    }
}

AutoShopping/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - خودرو بانک</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/AdminMasterPage.css" rel="stylesheet" />
    <link href="~/css/Main.css" rel="stylesheet" />
    <link href="~/lib/FileUpload/image-uploader.css" rel="stylesheet" />
    <link href="~/Awesome/fontawesome-pro-5.12.0-web-ulabs/css/all.css" rel="stylesheet" />
</head>
<body>
    <div class="container-fluid dirRtl">
        <div class="row justify-content-end">
            <div class="col-2 toolsMenu text-center">
                <div class="row">
                    <div class="siteLogo borderButtom">
                        <img src="~/Images/Logo.png" />
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="user mt-3 mb-2">
                        <img src="~/Images/userProfile.png" />
                        <h5 class="mt-3">کاربر عزیز خوش آمدید</h5>
                    </div>
                    <ul class="menu dirRtl">
                        <li>
                            <a href="#">اطلاعات پایه</a>
                            <ul>
                                <li>
                                    <a href="/Admin/Brand" id="first">برند</a>
                                </li>
                                <li>
                                    <a href="/Admin/Model">مدل</a>
                                </li>
                                <li>
                                    <a href="/Admin/Color">رنگ</a>
                                </li>
                                <li>
                                    <a href="/Admin/Car">افزودن ماشین</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="/Admin/Brand">مدیریت انبار</a>
                        </li>
                        <li>
                            <a href="/Admin/Brand">مدیریت سفارشات</a>
                        </li>
                        <li>
                            <a href="/Admin/Brand">مدیریت کاربران</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-10">
                <div class="row justify-content-center">
                    <div class="col-12">
                        <div class="row">
                            <div class="header borderButtom">
                                <a class="exitLink f22">خروج</a>
                                <a class="homeLink f22">ورود به صفحه اصلی</a>
                            </div>
                        </div>
                    </div>
                    @RenderBody()
                    @{
                        if (ViewBag.success == true)
                        {
                            <div id="Alert" class="alert alert-success alert-dismissible fade show mt-4 col-3" role="alert" style="position: fixed; bottom: 5px; left: 25px;">
                                <p class="text-center f20">عملیات با موفقیت انجام شد</p>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        }
                        else if (ViewBag.success == false)
                        {
                            <div id="Alert" class="alert alert-danger alert-dismissible fade show mt-4 col-3" role="alert" style="position: fixed; bottom: 5px; left: 25px;">
                                <p class="text-center f20">عملیات با خطا مواجه شد</p>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

    <script>
        //$("#first").addClass("backgroundSelect");
        //$("a").click(function () {
        //    $(".menu a").removeClass("backgroundSelect");
        //    $(this).addClass("backgroundSelect");
        //});

        var a = setTimeout(function () { $("#Alert").alert('close'); }, 3000);
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>

AutoShopping/Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> signInManager
@inject UserManager<IdentityUser> userManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - خودرو بانک</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/Awesome/fontawesome-pro-5.12.0-web-ulabs/css/all.css" rel="stylesheet" />

    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Login/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Login/css/main.css">
    <!--===============================================================================================-->

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container" dir="rtl">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <div class="siteLogo borderButtom">
                        <img src="~/Images/Logo.png" />
                    </div>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        @if (signInManager.IsSignedIn(User))
                        {
                            @if (User.IsInRole("Owner"))
                            {
                                <li class="nav-item">
                                    <a class="btn nav-link text-dark" asp-controller="ManageUser" asp-action="Index">مدیریت کاربران</a>
                                </li>
                                <li class="nav-item">
                                    <a class="btn nav-link text-dark" asp-controller="ManageRole" asp-action="Index">مدیریت نقش ها</a>
                                </li>
                            }
                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="SignOut" method="post">
                                    <button type="submit" class="btn nav-link text-dark">خروج</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">ثبت نام</a>
                            </li>
                            <span style="line-height: 2.8">/</span>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">ورود</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AutoShopping - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <!--===============================================================================================-->
    <script src="~/Login/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login/vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Login/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login/vendor/daterangepicker/moment.min.js"></script>
    <script src="~/Login/vendor/daterangepicker/daterangepicker.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login/vendor/countdowntime/countdowntime.js"></script>
    <!--===============================================================================================-->
    <script src="js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>